In [91]:
import torch

#RGB图片（批量大小*宽*高*通道）
#视频   （批量大小*时间*宽*高*通道）

In [92]:
#创建数组需要指定
  #形状
  #每个元素的数据类型 
  #每个元素的值

In [93]:
#数组访问元素
 #访问子区域[1:3,1]访问第1，2行的第一列之后的所有列
 #[::3,::2]表示访问所有行和列，但是行的步长是3，列的步长是2

In [94]:
import torch

In [95]:
#张量表示一个数值组成的数组，这个数组可能有多个维度
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [104]:
#可以通过张量的shape属性来访问张量的形状和张量中元素的总数
x.shape

torch.Size([12])

In [97]:
x.numel() #numel()返回张量中元素总个数

12

In [101]:
#可以使用reshape函数改变一个张量的形状而不改变元素数量和元素值
#reshape后的新变量地址还是之前的变量
X = x.reshape((3,4))
c = x
print(X)
print(id(c)==id(x))

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
True


In [19]:
#使用全0，全1，其他常量或者从特定分布中随机采样的数字
torch.zeros(2,3,4)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [29]:
#可以提供包含数值的python列表(可以使用嵌套列表)来为所需张量中的每个元素赋予确定的值
#使用tensor函数
torch.tensor([[2,1,4,3],[1,2,3,4],[4,3,2,1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [24]:
#常见的算术运算符都可以升级为按元素计算
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x+y, x-y, x*y, x/y, x**y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [25]:
#按元素做指数运算
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [35]:
# 可以使用cat()将多个张量连结在一起
X = torch.arange(12, dtype=torch.float32).reshape(3,4)
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X,Y),dim=0),torch.cat((X,Y),dim=1)#dim=0按行堆叠，dim=1按列堆叠

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [37]:
#通过逻辑运算符构建二元张量
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [40]:
#对张量中的所有元素求和会得到只有一个元素的张量
X.sum()

(tensor(66.), tensor(30.))

In [46]:
#即使形状不同，可以通过广播机制来执行按元素操作
#广播机制必须维度一样，比如都是二维
#广播机制会把每一维对应不一样的复制成一样的然后按元素操作(维度大的数必须是小的数的倍数，否则不能复制会报错)
a = torch.arange(3).reshape(3, 1)
b = torch.arange(2).reshape(1, 2)
a,b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [47]:
a+b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [48]:
print(X[-1])#访问第一行
print(X[1:3])#访问前两行

tensor([ 8.,  9., 10., 11.])
tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])


In [50]:
before = id(Y) #id(变量)相当于获取变量的指针
Y = Y+X
id(Y) == before #Y = Y+X的操作说明为新结果分配了新的内存

True

In [53]:
#对张量按元素操作相当于改写张量的元素，即执行原地操作
Z = torch.zeros_like(Y)
print("id(Z):", id(Z))
Z[:] = X+Y
print("id(Z):", id(Z))

id(Z): 140174571632424
id(Z): 140174571632424


In [54]:
#如果后续不重复使用X，可以使用X[:]=X+Y或X+=Y来减少操作的内存开销
before = id(X)
X += Y
id(X)==before

True

In [57]:
#转变为Numpy张量
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [62]:
#将大小为1的张量(二维，三维都可以)转换为python标量
a = torch.tensor([[3.5]])
a, a.item(), float(a), int(a)

(tensor([[3.5000]]), 3.5, 3.5, 3)

In [71]:
#数据预处理
#创建一个人工数据集，并存储在csv(逗号分隔值)文件
import os
os.makedirs(os.path.join('..','data'), exist_ok=True) #创建文件夹
data_file = os.path.join('..', 'data', 'house_tiny.csv')#创建文件
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n') #列名
    f.write('NA,Pave,127500\n')#每行表示一个数据样本
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

In [75]:
#从创建的csv文件中加载原始数据集
import pandas as pd
data = pd.read_csv(data_file)
print(data)

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000


In [78]:
#为了处理缺失的数据，典型的方法包括插值和删除，这里只考虑使用插值
inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2]
inputs = inputs.fillna(inputs.mean()) #将原数据为NA填入所在列的均值（只适用于列为数值型的列）
print(inputs)

   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN


In [84]:
#对于inputs中的类别或离散值，我们将“NaN”视为一个类别
inputs = pd.get_dummies(inputs, dummy_na=True) #对类别和离散值进行one hot 编码
print(inputs)

   NumRooms  Alley_Pave  Alley_nan
0       3.0           1          0
1       2.0           0          1
2       4.0           0          1
3       3.0           0          1


In [85]:
X, y = torch.tensor(inputs.values), torch.tensor(outputs.values)#将数据转变为张量，默认64位浮点数，但深度学习一般用32位浮点数这样计算比较快
X, y

(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500, 106000, 178100, 140000]))