In [1]:
#矩阵的物理意义是空间的扭曲
#特征向量指的是不被矩阵改变方向的向量，对称矩阵总是可以找到特征向量

In [5]:
import torch
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [6]:
x[3]

tensor(3)

In [7]:
len(x)

4

In [8]:
x.shape

torch.Size([4])

In [11]:
A = torch.arange(20).reshape(5,4) #创建一个矩阵
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [10]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [14]:
#向量是标量的推广，矩阵是向量的推广
#给定具有相同形状的任何两个张量，任何按元素二元运算的结果都将是相同形状的张量
A = torch.arange(20,dtype=torch.float32).reshape(5,4)
B = A.clone() #通过分配新内存，将A的一个副本分配给B
print(id(A)==id(B))
A, A+B

False


(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [15]:
#两个矩阵的按元素的乘法称为哈达玛积
A*B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [17]:
a = 2
X = torch.arange(24).reshape(2,3,4)
a + X, (a + X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

In [21]:
A = torch.arange(40).reshape(2,5,4)
print(A)
A.shape, A.sum()

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]],

        [[20, 21, 22, 23],
         [24, 25, 26, 27],
         [28, 29, 30, 31],
         [32, 33, 34, 35],
         [36, 37, 38, 39]]])


(torch.Size([2, 5, 4]), tensor(780))

In [24]:
#在维度0求和
A_sum_axis = A.sum(axis=0)
A_sum_axis

tensor([[20, 22, 24, 26],
        [28, 30, 32, 34],
        [36, 38, 40, 42],
        [44, 46, 48, 50],
        [52, 54, 56, 58]])

In [25]:
#在维度1求和
A_sum_axis = A.sum(axis=1)
A_sum_axis

tensor([[ 40,  45,  50,  55],
        [140, 145, 150, 155]])

In [26]:
A.sum(axis=[0,1])

tensor([180, 190, 200, 210])

In [43]:
A = A.float()
A.mean(), A.sum()/A.numel()

(tensor(19.5000), tensor(19.5000))

In [44]:
A.mean(axis=0), A.sum(axis=0)/A.shape[0]   #在0维度求均值

(tensor([[10., 11., 12., 13.],
         [14., 15., 16., 17.],
         [18., 19., 20., 21.],
         [22., 23., 24., 25.],
         [26., 27., 28., 29.]]),
 tensor([[10., 11., 12., 13.],
         [14., 15., 16., 17.],
         [18., 19., 20., 21.],
         [22., 23., 24., 25.],
         [26., 27., 28., 29.]]))

In [48]:
#计算总和或者均值时保持轴数不变：将keepdims设置为True
sum_A = A.sum(axis=1,keepdims=True)
sum_A.shape,sum_A

(torch.Size([2, 1, 4]),
 tensor([[[ 40.,  45.,  50.,  55.]],
 
         [[140., 145., 150., 155.]]]))

In [49]:
#将轴数保持不变可以通过广播将A/sum_A
A/sum_A

tensor([[[0.0000, 0.0222, 0.0400, 0.0545],
         [0.1000, 0.1111, 0.1200, 0.1273],
         [0.2000, 0.2000, 0.2000, 0.2000],
         [0.3000, 0.2889, 0.2800, 0.2727],
         [0.4000, 0.3778, 0.3600, 0.3455]],

        [[0.1429, 0.1448, 0.1467, 0.1484],
         [0.1714, 0.1724, 0.1733, 0.1742],
         [0.2000, 0.2000, 0.2000, 0.2000],
         [0.2286, 0.2276, 0.2267, 0.2258],
         [0.2571, 0.2552, 0.2533, 0.2516]]])

In [53]:
#将某个轴计算A元素的累计求和:把和累加下去，并保持维度不变
Y = A.cumsum(axis=2) 
Y

tensor([[[  0.,   1.,   3.,   6.],
         [  4.,   9.,  15.,  22.],
         [  8.,  17.,  27.,  38.],
         [ 12.,  25.,  39.,  54.],
         [ 16.,  33.,  51.,  70.]],

        [[ 20.,  41.,  63.,  86.],
         [ 24.,  49.,  75., 102.],
         [ 28.,  57.,  87., 118.],
         [ 32.,  65.,  99., 134.],
         [ 36.,  73., 111., 150.]]])

In [59]:
#点积是相同位置按元素乘积的和
y = torch.ones(4, dtype=torch.float32)
x = x.float() 
x, y, torch.dot(x,y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [60]:
#可以通过执行按元素乘法来表示两个向量的点积
torch.sum(x*y)

tensor(6.)

In [64]:
A = torch.arange(20,dtype=torch.float32).reshape(5,4)
#矩阵向量Ax是一个长度为m的列向量
A.shape, x.shape, torch.mv(A,x)

(torch.Size([5, 4]), torch.Size([4]), tensor([ 14.,  38.,  62.,  86., 110.]))

In [66]:
#矩阵乘法
B = torch.ones(4,3)
torch.mm(A,B)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

In [67]:
#L2范数是向量元素和的平方根
u = torch.tensor([3.0,-4.0])
torch.norm(u) #L2范数

tensor(5.)

In [68]:
#矩阵的弗罗贝尼斯范数是矩阵元素平方和的平方根
torch.norm(torch.ones(4,9))

tensor(6.)